CREATE TABLE IF NOT EXISTS `todos` ( 
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    todo VARCHAR(255) NOT NULL,
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    user_id INT NOT NULL,
    created_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES `users` (id) ON DELETE CASCADE
)